### ISSUE TITLE
Connect pods with IPv4/IPv6 address

### ISSUE THREAD

**Issue by Silvengs** [networkop/meshnet-cni#38]
Hello, I want to set both ipv4 and ipv6 addresses for the pod, I try the following configuration :
```yaml
# router-2
- uid: 2237123
  peer_pod: router-3
  local_intf: eth6
  peer_intf: eth6
  local_ip: 172.30.6.1/24
  peer_ip: 172.30.6.2/24
- uid: 2237123
  peer_pod: router-3
  local_intf: eth6
  peer_intf: eth6
  local_ip: 2001:DB8::1/64
  peer_ip: 2001:DB8::2/64
```
Then I found that only the ipv4 address was successfully configured :
```bash
# router-2
eth6      Link encap:Ethernet  HWaddr 1A:28:65:AF:B3:C2
          inet addr:172.30.6.1  Bcast:172.30.6.255  Mask:255.255.255.0
          inet6 addr: fe80::1828:65ff:feaf:b3c2/64 Scope:Link
```
I wonder how to configure ipv4 and ipv6 addresses at the same time, maybe like this :
```yaml
- uid: 2237123
  peer_pod: router-3
  local_intf: eth6
  peer_intf: eth6
  local_ip: 172.30.6.1/24,2001:DB8::1/64
  peer_ip: 172.30.6.2/24,2001:DB8::2/64
```
